#!/usr/bin/env bash
#
# Install the git pre-commit hook. Run once per clone — afterwards a normal
# `git commit` will invoke `scripts/precommit.sh` and refuse to record the
# commit if any check fails.
#
# To bypass intentionally (e.g. WIP commit before fixing the linter), use
# `git commit --no-verify`.
set -euo pipefail

cd "$(dirname "$0")/.."

if [[ ! -d .git ]]; then
  echo "scripts/install-hooks.sh: must be run from inside a git working tree" >&2
  exit 1
fi

HOOK=".git/hooks/pre-commit"
mkdir -p "$(dirname "$HOOK")"
cat > "$HOOK" <<'HOOK'
#!/usr/bin/env bash
# Auto-generated by scripts/install-hooks.sh — edit that file, not this one.
exec ./scripts/precommit.sh
HOOK
chmod +x "$HOOK"
echo "Installed pre-commit hook → $HOOK"
echo "Bypass once with: git commit --no-verify"
