#!/usr/bin/env bash
#
# Install the git pre-push hook. Run once per clone — afterwards a normal
# `git push` will invoke `scripts/precommit.sh` and refuse to push if any
# check fails. Running on push (not commit) keeps local commits fast while
# still gating everything before it reaches origin / CI.
#
# To bypass intentionally (e.g. pushing a WIP branch), use
# `git push --no-verify`.
set -euo pipefail

cd "$(dirname "$0")/.."

if [[ ! -d .git ]]; then
  echo "scripts/install-hooks.sh: must be run from inside a git working tree" >&2
  exit 1
fi

# Remove a legacy pre-commit hook from older checkouts so the gate doesn't
# also run on every commit.
if [[ -f .git/hooks/pre-commit ]] && grep -q "scripts/precommit.sh" .git/hooks/pre-commit; then
  rm -f .git/hooks/pre-commit
  echo "Removed legacy pre-commit hook (gate now runs on push)."
fi

HOOK=".git/hooks/pre-push"
mkdir -p "$(dirname "$HOOK")"
cat > "$HOOK" <<'HOOK'
#!/usr/bin/env bash
# Auto-generated by scripts/install-hooks.sh — edit that file, not this one.
exec ./scripts/precommit.sh
HOOK
chmod +x "$HOOK"
echo "Installed pre-push hook → $HOOK"
echo "Bypass once with: git push --no-verify"
